client/package-lock.json, client/package.json, client/src/App.css, client/src/App.jsx, client/src/component/Header.jsx, client/src/index.css
Hi, I've created Header as a component, with 2 main Buttons (Register and Lon in).
=> Create component : Header

client/src/App.jsx, client/src/component/Register.jsx, package-lock.json
added register page component based on mui template
=> added component register page based on mui template

client/src/component/Login.jsx
Added login component based on mui template
=> added login component based on mui template

client/src/App.jsx, client/src/component/Footer.jsx
Hi, I've created the Footer component, which is a sticky footer based on UI design.
=> create component Footer

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/component/Header.jsx, client/src/routes/Root.jsx
Added routes to Register and Login pages with header and footer to repeat on each page
=> routes for register and login buttons in header

client/src/component/Register.jsx
revise register component so that register and login pages have similar kinda styles. It's working now.
=> revise register component 

client/src/App.jsx, client/src/routes/Editor.jsx
Added Editor component to Routes and App
=> editor component

client/src/component/editor/Title.jsx, client/src/routes/Editor.jsx
So whatever user types in text input in Title component, it shows on the top of calendar in Editor page right away.
=> #58 connect text input in Title with Editor

client/src/component/editor/Background.jsx, client/src/routes/Editor.jsx
choose a color with color picker in Background menu and add it real time to calendar area
=> add background color to calendar area

client/src/routes/Editor.jsx
created folder for related components, commented out unneeded code for now
=> preset for single hatch menu

client/src/component/UserAvatar.jsx, client/src/routes/Editor.jsx, client/src/routes/User.jsx, server/firebase.js
Restyle User Dashboard based on UI Design
=> #59 restyle user dashboard

client/src/component/editor/Hatch.jsx, client/src/component/hatchEditor/WidthHeight.jsx, client/src/routes/Editor.jsx
=> hatch dimensions menu

client/src/component/editor/Hatch.jsx, client/src/component/hatchEditor/BasicModal.jsx, client/src/routes/Editor.jsx
=> changed button name, added close function to backToCalendar button

client/src/component/hatchEditor/HatchNavigation.jsx, client/src/routes/Editor.jsx
functionality to buttons previous and next will be added later
=> hatch navigation bar, only layout

client/src/component/hatchEditor/Video.jsx, client/src/routes/Editor.jsx
=> add video menu to single hatch -layout 

client/src/component/hatchEditor/BasicModal.jsx, client/src/component/hatchEditor/TextEditor.jsx, client/src/routes/Editor.jsx
Modify Title input, Text input with conditional setting, modify styling as well, and connect the TextEditor with BasicModal.
=> modify TextEditor and connect it with Modal

client/src/component/Footer.jsx, client/src/component/Header.jsx, client/src/index.css, client/src/routes/Editor.jsx, client/src/routes/Home.jsx, client/src/routes/Login.jsx, client/src/routes/Register.jsx, client/src/routes/User.jsx
Refine styling in Header, Footer, Home, User, Login, Register.
=> #85 restyle header footer and table in user

client/src/component/Header.jsx
made spacing the same as it is between logo and the left end of header
=> fix spacing between register/log out button and the right end of header

client/src/App.jsx, client/src/component/editor/Background.jsx, client/src/component/editor/EditorHeader.jsx, client/src/component/editor/Hatch.jsx, client/src/routes/Editor.jsx, client/src/routes/Root.jsx
Toggle calendar between editor and preview modes.
=> Preview calendar

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/component/adminPanel/Chart.jsx, client/src/component/adminPanel/Deposits.jsx, client/src/component/adminPanel/Orders.jsx, client/src/routes/AdminPanel.jsx, client/src/routes/Editor.jsx, server/firebase.js
Hi all, I created a new route AdminPanel with some fake data.
=> #45 create new route admin panel

client/src/component/editor/Calender.jsx, client/src/component/editor/Hatch.jsx, client/src/component/editor/Hatch.module.css
added door animation for opening hatches
=> added animation for opening hatches

client/src/component/editor/DateCalendar.jsx, client/src/features/calendarSlice.js
with toISOString() which redux asked for didn't show dates on app, so deleted toISOString()
=> fixed date range

client/package-lock.json, client/package.json, client/src/routes/Home.jsx
update home page- left text aligned, to keep design consistency
=> update home page

client/src/component/hatchEditor/TextEditor.jsx
settings bold, italic, underlined  modify input in title and text fields, but no button highlight for chosen settings
=> bold, italic, underlined styling fixed

client/src/component/hatchEditor/BasicModal.jsx, client/src/component/hatchEditor/UploadImage.jsx, client/src/features/hatchSlice.js, client/src/routes/Editor.jsx
replaced useState with redux for hatch images
=> set redux for hatch image

client/src/component/editor/EditorHeader.jsx, client/src/features/calendarSlice.js, client/src/routes/User.jsx, server/utils.js
setDoc() creates a new doc in firebase if there is no docs with such a number or overwrites existing one
=> save calendar settings to firebase

client/src/component/editor/EditorHeader.jsx, client/src/routes/Editor.jsx, server/utils.js
added checks if properties "" or {} instead of underfined
=> fixed editor page reload break

client/src/component/Header.jsx, client/src/component/Instruction.jsx, client/src/routes/Login.jsx, client/src/routes/Register.jsx
change font size in Instruction, fix border colour on hovered in forms on Login and Register, revise Header component to render only one button conditionally
=> #114 refine UI on instruction and login set conditional button rendering on login

client/src/component/hatchEditor/HatchNavigation.jsx, client/src/routes/Editor.jsx
add functionality to the arrow buttons to navigate between hatches
=> hatch navigation

client/src/component/footer/ContactForm.jsx, client/src/component/footer/ContactModal.jsx
contact form redesigend keeping the ui design consistency
=> contact form  ui fix

client/src/component/Header.jsx
Not showing tabs for Instruction and Pricing on user route
=> user route tabs for header

client/src/component/editor/DateCalendar.jsx, client/src/routes/Editor.jsx
limit the hatch number from 1 to 31
=> limit the hatch number
